categories_list = [
	'Accommodations - Boutique Hotels',
	'Accommodations - Dive Hotels',
	'Accommodations - Eco Hotels',
	'Accommodations - Extended Stay',
	'Accommodations - Hostels',
	'Accommodations - Hotels',
	'Accommodations - Motels',
	'Accommodations - Resorts',
	'Accommodations - Time Shares & Condominiums',
	'Animal Hospitals',
	'Artists',
	'Automotive - Auto Dealers – New',
	'Automotive - Auto Dealers – Used',
	'Automotive - Auto Parts & Accessories',
	'Automotive - Detail & Carwash',
	'Automotive - Motorcycle Sales & Repair Rental & Leasing',
	'Automotive - Service, Repair & Parts Towing',
	'Banking & Financial Institutions',
	'Barber & Beauty Salons',
	'Bike Repair',
	'Catering & Supplies',
	'Computer Programming & Support Consumer',
	'Construction & Contractors - Architects',
	'Construction & Contractors - Blasting & Demolition',
	'Construction & Contractors - Building Materials & Supplies',
	'Construction & Contractors - Construction Companies',
	'Construction & Contractors - Electricians',
	'Construction & Contractors - Engineers & Surveyors',
	'Construction & Contractors - Landscape Architects',
	'Construction & Contractors - Plaster & Concrete',
	'Construction & Contractors - Plumbers',
	'Construction & Contractors - Roofers',
	'Consultants',
	'Distribution, Import/Export Manufacturing',
	'Dry Cleaners & Laundromats',
	'Educational - Adult & Continuing Education',
	'Educational - Early Childhood Education',
	'Educational - Educational Resources',
	'Educational - Other Educational',
	'Employment Agencies',
	'Equipment Rentals',
	'Exercise & Fitness',
	'Financial Services - Accountants',
	'Funeral Service Providers & Cemeteries',
	'Gas Stations',
	'Government Agencies',
	'Grocery - Cheese & Dairy',
	'Grocery - Bakery',
	'Grocery - Fruit',
	'Grocery - General',
	'Grocery - Health Food',
	'Grocery - Meat',
	'Grocery - Misc',
	'Grocery - Seafood',
	'Grocery - Specialty',
	'Grocery - Vegetable',
	'Health & Medicine - Acupuncture',
	'Health & Medicine - Chiropractic',
	'Health & Medicine - Dental',
	'Health & Medicine - Diet & Nutrition',
	'Health & Medicine - Drug & Vitamin Stores',
	'Health & Medicine - Hospitals',
	'Health & Medicine - Imaging & Diagnostic',
	'Health & Medicine - Massage Therapy',
	'Health & Medicine - Medical Clinics',
	'Health & Medicine - Mental Health',
	'Health & Medicine - Nurse',
	'Health & Medicine - Optical',
	'Health & Medicine - Other',
	'Health & Medicine - Pediatrician',
	'Health & Medicine - Pharmacy',
	'Health & Medicine - Physical Therapy',
	'Health & Medicine - Physicians & Assistants',
	'Health & Medicine - Podiatry',
	'Health & Medicine - Social Worker',
	'Home Improvements & Repairs',
	'Insurance',
	'Landscape & Lawn Service',
	'Legal Services - Attorneys',
	'Legal Services - Other Legal',
	'Manufacturing, Wholesale, Distribution',
	'Marketing',
	'Massage & Body Works',
	'Media & Communications - Cable Service Providers',
	'Media & Communications - Internet Service Providers',
	'Media & Communications - Radio Broadcasting',
	'Media & Communications - Telephone Service Providers',
	'Media & Communications - Television Broadcasting',
	'Miscellaneous',
	'Nail Salons',
	'Nonprofit',
	'Personal Care & Services',
	'Pest Control',
	'Pool Supplies & Service',
	'Printing & Publishing',
	'Real Estate',
	'Real Estate - Agencies & Brokerage',
	'Real Estate - Agents & Brokers',
	'Real Estate - Apartment & Home Rental',
	'Real Estate - Mortgage Broker & Lender',
	'Real Estate - Property Management',
	'Real Estate - Title Company',
	'Recreation',
	'Recreation -  Golf Courses',
	'Recreation - Bars',
	'Recreation - Beach Clubs',
	'Recreation - Cinemas',
	'Recreation - Event Planners & Supplies',
	'Recreation - Night Clubs',
	'Recreation - Other',
	'Recreation - Venues',
	'Restaurants',
	'Restaurants - American',
	'Restaurants - Chinese',
	'Restaurants - Desserts',
	'Restaurants - Fast Food',
	'Restaurants - Fine Dining',
	'Restaurants - Healthy',
	'Restaurants - Italian',
	'Restaurants - Mexican',
	'Restaurants - Other',
	'Restaurants - Pizza',
	'Restaurants - Seafood',
	'Restaurants - Sushi',
	'Retail',
	'Retail - Antiques & Collectibles',
	'Retail - Arts & Crafts',
	'Retail - Baby',
	'Retail - Bakery',
	'Retail - Beauty & Fragrances',
	'Retail - Beverage & Tobacco',
	'Retail - Books & Magazines',
	'Retail - Candy',
	'Retail - Cards & Gifts',
	'Retail - Children\'s Clothing',
	'Retail - Computers & Electronics',
	'Retail - Convenience Store',
	'Retail - Crafts, Hobbies & Sports',
	'Retail - Department Stores',
	'Retail - Flower Shops',
	'Retail - General',
	'Retail - Gifts',
	'Retail - Hardware Stores',
	'Retail - Home & Garden',
	'Retail - Home Furnishings',
	'Retail - Jewelry',
	'Retail - Men\'s Clothing',
	'Retail - Office Supplies',
	'Retail - Other (not elsewhere classified)',
	'Retail - Pet and Animal Supplies',
	'Retail - Religion & Spirituality (for profit)',
	'Retail - Shoes',
	'Retail - Specialty',
	'Retail - Sports & Outdoors',
	'Retail - Toys & Hobbies',
	'Retail - Women\'s Clothing',
	'Security System & Services',
	'Services - Other',
	'Shipping - Packing & Shipping',
	'Shoe Repairs',
	'Sustainable Businesses',
	'Tailors',
	'Transportation - Airlines',
	'Transportation - Car Rentals',
	'Transportation - Cargo',
	'Transportation - Charter Bus Services',
	'Transportation - Ferries',
	'Transportation - Motorcycle Rental',
	'Transportation - Moving Services',
	'Transportation - Scooter Rental',
	'Transportation - Shuttles',
	'Transportation - Taxi',
	'Translation Services',
	'Travel & Tourism - Charter Boats',
	'Travel & Tourism - Cruise Lines',
	'Travel & Tourism - Dive Companies',
	'Travel & Tourism - Tour Operators',
	'Travel & Tourism - Travel Agents',
	'Utility Companies',
	'Veterinary & Animal Surgeons',
	'Wholesale'
]

categories_list.each do |name|
	Category.create( name: name )
end
